name: main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: "Force HTTPS"
      run: git config --global url."https://github".insteadOf ssh://git@github

    - name: "Checkout sources"
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: "Setup NodeJS"
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"

    - name: "Install dependencies"
      run: yarn install

    - name: "Build"
      run: yarn build

    - name: "Run tests"
      run: yarn test

    - name: 'Commit and push build directory'
      uses: stefanzweifel/git-auto-commit-action@v5 
      with:
        file_pattern: 'build/*'
